# Generated by Django 4.1.3 on 2023-07-30 06:46

from django.db import migrations, models
import polls.storages_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('date', models.CharField(max_length=200)),
                ('urlCTA', models.CharField(max_length=200)),
                ('imgPost', models.FileField(default='/blogger/cargo-ship.png', storage=polls.storages_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
